<?php
namespace PHPSTORM_META;

# START OF Hauptsache\Typo3Environment\Generator\PhpStormMetaGenerator
# THIS AREA IS AUTO GENERATED BY hauptsache/typo3-environment

// Hint that makeInstance will return an instance of the class it gets passed
override(\TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(0), map([
    '' => '@'
]));

// Hint that object manager will return an instance of the class it gets passed
override(\TYPO3\CMS\Extbase\Object\ObjectManager::get(0), map([
    '' => '@'
]));

# END OF Hauptsache\Typo3Environment\Generator\PhpStormMetaGenerator
