
# START OF Hn\Typo3Environment\Generator\MakefileGenerator
# THIS AREA IS AUTO GENERATED BY hauptsache/typo3-environment
LOCAL_COMPOSER?=docker-compose run --rm --no-deps php composer
LOCAL_TYPO3CMS?=docker-compose exec php vendor/bin/typo3cms
ENVIRONMENT?=development
LOCAL_DOCKER_COMPOSE?=docker-compose
LOCAL_OPEN_ADDRESS?=open

.PHONY: serve start install cc clean stop


serve: start
	$(LOCAL_OPEN_ADDRESS) http://localhost:8080/


start: install
	$(LOCAL_DOCKER_COMPOSE) up -d
	$(LOCAL_DOCKER_COMPOSE) exec db bash -c 'while ! mysql -uroot -p$$MYSQL_ROOT_PASSWORD -e"SELECT 1" > /dev/null 2>&1; do echo -n .; sleep 1; done; echo mysql online'
	if [ ! -f 'web/typo3conf/LocalConfiguration.php' ]; then $(LOCAL_TYPO3CMS) install:setup --site-setup-type=site; fi


install:
ifeq ($(ENVIRONMENT), development)
	$(LOCAL_COMPOSER) install --dev
	$(LOCAL_DOCKER_COMPOSE) build
else
	$(LOCAL_COMPOSER) install --no-dev --prefer-dist --optimize-autoloader --classmap-authoritative
endif


cc: start
	$(LOCAL_TYPO3CMS) database:updateschema --verbose
	$(LOCAL_TYPO3CMS) cache:flush
	$(LOCAL_TYPO3CMS) extension:setupactive


clean: stop
	$(LOCAL_DOCKER_COMPOSE) down -v
	rm -rf 'vendor'
	rm -f 'web/FIRST_INSTALL'
	rm -f 'web/typo3conf/ENABLE_INSTALL_TOOL'
	rm -rf 'web/typo3temp'
	rm -f 'web/typo3conf/LocalConfiguration.php'
	rm -f 'web/typo3conf/PackageStates.php'


stop:
	$(LOCAL_DOCKER_COMPOSE) down


# END OF Hn\Typo3Environment\Generator\MakefileGenerator

test: install
	$(LOCAL_DOCKER_COMPOSE) run --rm --no-deps php vendor/bin/phpunit Tests
